// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagement.Data;

#nullable disable

namespace StockManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125123952_RemoveQuantityAddSerialNumber")]
    partial class RemoveQuantityAddSerialNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "admin",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "admin",
                            Name = "Cars"
                        });
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "A high-end smartphone with amazing features",
                            Name = "Smartphone XYZ",
                            Price = 799.00m,
                            SerialNumber = "5a5d2376-c23a-4455-b388-8e36ae2ccfc6"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedBy = "admin",
                            Description = "A premium leather jacket for winter",
                            Name = "Stylish Leather Jacket",
                            Price = 120.00m,
                            SerialNumber = "0f9bac5c-a46b-403a-8a68-39ee78d1409f"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "Noise-canceling wireless headphones",
                            Name = "Bluetooth Headphones",
                            Price = 150.00m,
                            SerialNumber = "fcb71ce4-25d0-4031-9053-eadca828ec6e"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedBy = "admin",
                            Description = "A cozy winter jacket to keep you warm",
                            Name = "Winter Jacket",
                            Price = 80.00m,
                            SerialNumber = "a3f0a58f-7400-43ee-856a-5c8ebe901be9"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "A smartwatch with fitness tracking and notifications",
                            Name = "Smart Watch",
                            Price = 200.00m,
                            SerialNumber = "36e3f9c5-e5b9-4f16-959b-a2bcdc76d701"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "Ultra HD LED TV with smart features",
                            Name = "LED TV",
                            Price = 500.00m,
                            SerialNumber = "b7483350-cce4-4f04-b9a4-443d16df038c"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Fast boiling electric kettle for quick tea or coffee",
                            Name = "Electric Kettle",
                            Price = 30.00m,
                            SerialNumber = "50dc923f-c588-48a6-b981-4781f90a17d6"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Energy-efficient fridge with large capacity",
                            Name = "Refrigerator",
                            Price = 800.00m,
                            SerialNumber = "e3b7d25f-5277-4e07-850f-8b9ff4855a36"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "Water-resistant portable Bluetooth speaker",
                            Name = "Portable Speaker",
                            Price = 90.00m,
                            SerialNumber = "8386f46f-3403-4196-a1cd-404722bf7d91"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Healthy cooking with this modern air fryer",
                            Name = "Air Fryer",
                            Price = 150.00m,
                            SerialNumber = "4db3ff0f-07ab-42f7-a0d2-6e95a13215a8"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Sonic electric toothbrush for cleaner teeth",
                            Name = "Electric Toothbrush",
                            Price = 60.00m,
                            SerialNumber = "c138a585-3959-428b-8c1b-e75e6a9698b6"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "High-quality digital camera for photography enthusiasts",
                            Name = "Digital Camera",
                            Price = 400.00m,
                            SerialNumber = "e2730a18-0e01-4e6b-8b19-fa4c1be2f491"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "Ergonomic gaming mouse with customizable buttons",
                            Name = "Gaming Mouse",
                            Price = 50.00m,
                            SerialNumber = "72a6e83c-a5e1-4d62-a3db-3792ab30fda7"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Adjustable desk lamp with LED lighting",
                            Name = "LED Desk Lamp",
                            Price = 40.00m,
                            SerialNumber = "13d2eeaa-a58f-4273-a283-004a1c87a364"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedBy = "admin",
                            Description = "Magnetic phone mount for easy car navigation",
                            Name = "Car Phone Mount",
                            Price = 20.00m,
                            SerialNumber = "c696ada0-c36c-4093-b628-3cf22475fc60"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedBy = "admin",
                            Description = "Spacious 4-person camping tent with waterproof design",
                            Name = "Camping Tent",
                            Price = 120.00m,
                            SerialNumber = "7be829fb-1003-421f-bfda-cb1b46a2b718"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Wi-Fi enabled smart thermostat for energy savings",
                            Name = "Smart Thermostat",
                            Price = 250.00m,
                            SerialNumber = "4ffd8cbc-b5bd-42f2-bba0-47268e379132"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "High-capacity portable power bank for smartphones",
                            Name = "Portable Charger",
                            Price = 40.00m,
                            SerialNumber = "4f3f75dc-fd87-4468-b1c7-a550b7516aea"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedBy = "admin",
                            Description = "Durable and spacious backpack for laptops and accessories",
                            Name = "Laptop Backpack",
                            Price = 40.00m,
                            SerialNumber = "f76ef7ff-240a-4989-b7d8-c3575939a808"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedBy = "admin",
                            Description = "Sleek modern wall clock with a minimal design",
                            Name = "Wall Clock",
                            Price = 25.00m,
                            SerialNumber = "76881290-6c05-495a-8160-027bffd4323f"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Professional blow dryer with multiple heat settings",
                            Name = "Hair Dryer",
                            Price = 70.00m,
                            SerialNumber = "b55dc73f-d093-4af1-bb0a-dd0ca4abf9f0"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Blend your smoothies on the go with this portable blender",
                            Name = "Portable Blender",
                            Price = 45.00m,
                            SerialNumber = "1f7a46b6-131f-4454-aa08-f091a5b7980b"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedBy = "admin",
                            Description = "Portable camping stove for outdoor cooking",
                            Name = "Camping Stove",
                            Price = 70.00m,
                            SerialNumber = "7cdea6eb-d8a5-4db9-b133-a823fd29a593"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Description = "Wearable fitness tracker to monitor daily activities",
                            Name = "Fitness Tracker",
                            Price = 130.00m,
                            SerialNumber = "cc02b812-8602-47ae-9d84-9093ba430e4b"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedBy = "admin",
                            Description = "Ergonomic gaming chair with adjustable armrests",
                            Name = "Gaming Chair",
                            Price = 180.00m,
                            SerialNumber = "c8e7458e-a7e3-4beb-9650-6322e7f21b43"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreatedBy = "admin",
                            Description = "Eco-friendly solar charger for your devices",
                            Name = "Solar Charger",
                            Price = 35.00m,
                            SerialNumber = "a3c6fc60-5e39-4585-b209-c57e5a78e1c5"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            CreatedBy = "admin",
                            Description = "Home air purifier with HEPA filter for cleaner air",
                            Name = "Air Purifier",
                            Price = 150.00m,
                            SerialNumber = "eab010d3-1af2-465e-8c74-8a2b1cc4eab8"
                        });
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            FirstName = "admin",
                            IsFirstLogin = false,
                            LastName = "admin",
                            Password = "AQAAAAIAAYagAAAAEDum2iRiutnvrIxksx260617eJZ5/frmQHNpcaEP27j39MWIxPKHhv2ntx5/nfMeTw==",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            FirstName = "user",
                            IsFirstLogin = false,
                            LastName = "user",
                            Password = "AQAAAAIAAYagAAAAEKdGQFx6nUc7WD3b5LU2dBKnJm0+JoJeT386V26RG+9LtONU47329rCacuooACFtnQ==",
                            Role = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
